/**
 * @file Automatically generated by scripts/generate-preload-types.mjs
 * Do not edit this file manually.
 */

import { ElectronAPI } from '@electron-toolkit/preload'
import type { TestAPI, KnowledgeLibraryAPI, KnowledgeConfigAPI, FileAPI, FileImportAPI, UserConfigAPI, MinerUAPI, ChunkingAPI, ModelConfigAPI, // Electron 文件路径工具
  utilsAPI } from './types'

declare global {
  interface Window {
    electron: ElectronAPI
    api: {
      test: TestAPI
      knowledgeLibrary: KnowledgeLibraryAPI
      knowledgeConfig: KnowledgeConfigAPI
      file: FileAPI
      fileImport: FileImportAPI
      userConfig: UserConfigAPI
      minerU: MinerUAPI
      chunking: ChunkingAPI
      modelConfig: ModelConfigAPI
      // Electron 文件路径工具
  utils: // Electron 文件路径工具
  utilsAPI
    }
  }
}

export {}
