/**
 * @file Automatically generated by scripts/generate-preload-types.mjs
 * Do not edit this file manually.
 */

import { ElectronAPI } from '@electron-toolkit/preload'
import type {
  TestAPI,
  KnowledgeLibraryAPI,
  FileAPI,
  FileImportAPI,
  UserConfigAPI,
  MinerUAPI, // Electron 文件路径工具
  utilsAPI
} from './types'

declare global {
  interface Window {
    electron: ElectronAPI
    api: {
      test: TestAPI
      knowledgeLibrary: KnowledgeLibraryAPI
      file: FileAPI
      fileImport: FileImportAPI
      userConfig: UserConfigAPI
      minerU: MinerUAPI
      // Electron 文件路径工具
      utils: utilsAPI // Electron 文件路径工具
    }
  }
}

export {}
