/**
 * @file Automatically generated by scripts/generate-preload-types.mjs
 * Do not edit this file manually.
 */

import { ElectronAPI } from '@electron-toolkit/preload'
import type {
  TestAPI,
  KnowledgeLibraryAPI,
  FileAPI,
  FileImportAPI,
  UserConfigAPI,
  MinerUAPI,
  ChunkingAPI,
  ModelConfigAPI,
  KnowledgeConfigAPI,
  TaskMonitorAPI,
  EmbeddingAPI,
  utilsAPI
} from './types'

declare global {
  interface Window {
    electron: ElectronAPI
    api: {
      test: TestAPI
      knowledgeLibrary: KnowledgeLibraryAPI
      file: FileAPI
      fileImport: FileImportAPI
      userConfig: UserConfigAPI
      minerU: MinerUAPI
      chunking: ChunkingAPI
      modelConfig: ModelConfigAPI
      knowledgeConfig: KnowledgeConfigAPI
      taskMonitor: TaskMonitorAPI
      embedding: EmbeddingAPI
      utils: utilsAPI
    }
  }
}

export {}
